name: imprint
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
    # I could’ve left the requirements.txt inline inside environment.yml, but
    # splitting it out has the advantage that Renovate bot will
    # auto-update a requirements.txt file but won’t auto-update an
    # environment.yml
  - pip:
    - -r requirements.txt