channels:
  - conda-forge
dependencies:
  - seaborn
  - line_profiler
  - sympy
  - pandas
  - cython
  - radian

# dependencies only available from pip.
# - cppimport is only used for a few things in the research folder so we don't
#   need to worry about it much. That code could be removed safely.
# - pybind11[global] is only used by the same cppimport code. 
  - pip:
    - "pybind11[global]"
    - cppimport