name: confirm
channels:
  - conda-forge
dependencies:
# essentials
  - python
  - setuptools
  - jupyterlab
  - numpy
  - scipy
  - matplotlib

# C++ toolchain
  - cxx-compiler 
  - clang-tools
  - bazel 

# essential dev tools
  - pytest
  - pre-commit
  - black
  - flake8
  - isort
  - jupytext
  - pip

# numerical tools
  - jax==0.3.7
  - jaxlib==0.3.7
  - numpyro