name: confirm
channels:
  - conda-forge
dependencies:
  # essentials
  - python=3.10
  - pip
  - pip:
    - -r requirements.txt

  # - setuptools
  # - jupyterlab
  # - numpy
  # - scipy
  # - sympy
  # - matplotlib
  # - typer

  # # essential dev tools
  # - pytest
  # - pre-commit
  # - black
  # - flake8
  # - isort
  # - jupytext

  # # dependencies only available from pip.
  # # - conda-forge gpu jax support is fairly new and might be fragile,
  # #   and I can't get it to consistently install correctly.
  # #   https://github.com/conda-forge/jaxlib-feedstock/issues/34
  # #   so we install jax and numpyro from pypi instead. Importantly, we install a
  # #   CUDA jax here. If your system doesn't support CUDA, the ./install.sh script
  # #   will overwrite with a CPU jax.
  # - pip:
  #   # - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
  #   - "jax[cuda]"
  #   - "numpyro[cuda]"
