name: confirm
channels:
  - conda-forge
dependencies:
# essentials
  - python
  - setuptools
  - jupyterlab
  - numpy
  - scipy
  - matplotlib

# C++ toolchain
  - cxx-compiler 
  - clang-tools
  - bazel 

# essential dev tools
  - pytest
  - pre-commit
  - black
  - flake8
  - isort
  - jupytext
  - pip

# dependencies only available from pip.
# - cppimport is only used for a few things in the research folder so we don't
#   need to worry about it much. That code could be removed safely.
# - pybind11[global] is only used by the same cppimport code. 
# - conda-forge gpu jax support is fairly new and might be fragile,
#   and I can't get it to consistently install correctly.
#   https://github.com/conda-forge/jaxlib-feedstock/issues/34
#   so we install jax and numpyro from pypi instead
#   IMPORTANTLY, we install a cpu jax here. If you want gpu jax, install an
#   identical version before building from this environment.yml. Then, pip will
#   not reinstall here because the package is already installed. This has
#   already been done for our devimage.
  - pip:
    - "jax[cpu]==0.3.14"
    - numpyro
    - "pybind11[global]"
    - cppimport