name: confirm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - setuptools
  - numpy
  - scipy
  - sympy
  - matplotlib
  - typer
  - pytest
  - pre-commit
  - pip

  - pip:
      - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
      - "jax[cuda]"
      - "numpyro[cuda]"