channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - matplotlib
  - pandas
  - sympy
  - pytest
  - pre-commit
  - black-jupyter
  - flake8
  - isort
  - jupytext
  - line_profiler
  - pip:
    - poetry==1.2.2
    - memory_profiler
