#!/bin/bash

# Running on codespaces, the gpus=all runArg causes problems, so we duplicate
# the configuration in this subfolder.
echo "// Autogenerated, please see copy_default.sh!" > ./devcontainer.json
for i in {1..10}; do
    echo "// Autogenerated, please see copy_default.sh!" >> ./devcontainer.json;
done
sed '/gpus=all/d' ../devcontainer.json >> ./devcontainer.json