[tool.poetry]
name = "confirm"
version = "0.1.0"
description = ""
authors = ["Confirm Solutions <research@confirmsol.org>"]

[tool.poetry.dependencies]
python = "~3.10"
numpy = "^1.23.4"
scipy = "^1.9.3"
sympy = "^1.11.1"
pandas = "^1.5.1"
jax = "0.3.24"
numpyro = "^0.10.1"
jaxlib = [
    {version = "0.3.22", platform = "darwin", source="pypi"},
    {version = "0.3.24+cuda11.cudnn82", platform = "linux", source="jax"}
]
rich = "^12.6.0"
duckdb = "^0.6.0"

[[tool.poetry.source]]
name = "jax"
url = "https://storage.googleapis.com/jax-releases/jax_cuda_releases.html"
default = false
secondary = false

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"