name: Lint

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "research/**"
      - "**.ipynb"
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "research/**"
      - "**.ipynb"
      - "**.md"
jobs:
  test:
    if: github.event.pull_request.draft == false
    timeout-minutes: 15
    strategy:
      fail-fast: false
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install pre-commit
        run: pipx install pre-commit

      - name: set PY
        run: echo "PY=$(python -VV | sha256sum | cut -d' ' -f1)" >> $GITHUB_ENV
          
      - name: Cache pre-commit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.PY }}|${{ hashFiles('.pre-commit-config.yaml') }}
        id: precommitcache
          
      # The hooks will be installed automatically when pre-commit run is
      # called. But it's nice to do it separately for more visibility in the
      # GitHub interface into where a failure happens and how long each step
      # takes.
      - name: Install pre-commit hooks
        run: pre-commit install --install-hooks

      - name: Run all pre-commit checks on all files
        run: pre-commit run --color=always -a
        if: github.ref == 'refs/heads/main'