
name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  schedule:
    # Runs at 02:57am on Monday at Thursday
    - cron: '57 2 * * 1,4'
jobs:
  test:
    timeout-minutes: 60
    name: End to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'poetry-e2e'

      - name: Update environment
        run: |
          poetry env use ${{ matrix.python-version }} && poetry install --with=test,cloud,cloud_dev

      - name: Run tests
        run: poetry run python confirm/cloud/e2e_runner.py