
name: E2E

on:
  schedule:
    # Runs at 02:57am every day.
    - cron: '57 2 * * *'
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    name: End to end tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Update environment
        run: |
          poetry env use ${{ matrix.python-version }} && poetry install --with=test,cloud,cloud_dev

      - name: Run tests
        run: |
          poetry run modal token set \
            --token-id ${{ secrets.MODAL_TOKEN_ID }} \
            --token-secret ${{ secrets.MODAL_TOKEN_SECRET }}
            # --env=confirm_solutions
          poetry run python confirm/cloud/modal_test_runner.py --runslow tests imprint/tests
        
      - name: Clear Clickhouse Test DBs
        run: |
          poetry run python confirm/cloud/clear_test_dbs.py